services:
  flask-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    image: flask-dev-image
    container_name: flaks-dev-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - flask-network
    env_file:
      - ./.env
    tty: true

  flask-prod:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    image: flask-prod-image
    container_name: flaks-prod-container
    ports:
      - "80:80"
    volumes:
      - .:/app
    networks:
      - flask-network
    env_file:
      - ./.env
    tty: true
  
  flask-repo:
    image: ramamanohark555/flask_restful_api_repo:latest
    container_name: flask-repo-container
    networks:
      - flask-network
    env_file:
      - ./.env
    tty: true

networks:
  flask-network:
    driver: bridge