services:
  flask-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    image: ramamanohark555/flask_restful_api_repo
    container_name: flaks-dev-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - flask-network
    tty: true

  flask-prod:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    image: ramamanohark555/flask_restful_api_repo
    container_name: flaks-prod-container
    ports:
      - "80:80"
    volumes:
      - .:/app
    networks:
      - flask-network
    tty: true

networks:
  flask-network:
    driver: bridge